name: GitHub Classroom Workflow
on: [push]
jobs:
  build:    
    name: Autograding
    runs-on: ubuntu-18.04
    container: rocker/verse:latest
    defaults:
      run:
        shell: Rscript {0}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - uses: education/autograding@v1
      - name: Install dependencies
        run: |
          install.packages(c("testthat","tidyverse"))
        shell: Rscript {0}
      - name: Run Tests via bash
        run: tests/test.sh
        shell: bash
      - name: Run Testthat
        run: source("tests/testthat.R")
        shell: Rscript {0}
