name: Run Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      GITHUB_PAT: ${{secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          install.packages(c("testthat","tidyverse"))
        shell: Rscript {0}
      - name: Run Testthat
        run: source("tests/testthat.R")
        shell: Rscript {0}
    container: rocker/verse:latest
      