name: Run Tests
'on':  push
jobs:
  build:
    container: rocker/verse:latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          install.packages(c("testthat","tidyverse"))
        shell: Rscript {0}
      - name: Run Testthat
        run: source("tests/testthat.R")
        shell: Rscript {0}
      